FROM node:24 AS base
RUN corepack enable && npm install --global turbo@^1.8.3
WORKDIR /app

# Generate a pruned workspace
FROM base as pruned-workspace
COPY ./ ./
RUN turbo prune --scope=creatorsgarten-wiki --docker

# Install dependencies
FROM base as deps
COPY .gitignore .
COPY --from=pruned-workspace /app/out/json/ ./
COPY --from=pruned-workspace /app/out/pnpm-lock.yaml ./
COPY --from=pruned-workspace /app/out/pnpm-workspace.yaml ./
RUN pnpm install

# Build the project
FROM deps as app
COPY --from=pruned-workspace /app/out/full/ ./
RUN pnpm exec turbo build --filter=creatorsgarten-wiki
WORKDIR /app/wiki.creatorsgarten.org
CMD node dist/server/entry.mjs
