[build]
  command = "pnpm run build"
  publish = "contentsgarten.netlify.app/public"

[functions]
  directory = "contentsgarten.netlify.app/.netlify/functions-internal"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
