packages:
  - 'packages/*'
  - 'contentsgarten.netlify.app'
  - 'wiki.creatorsgarten.org'

allowBuilds:
  '@sentry/cli': true
  deasync: true
  esbuild: true
  protobufjs: true
  sharp: true

overrides:
  '@types/hast': '^3.0.5'
  '@sinclair/typebox': '^0.34.0'
